### ISSUE TITLE
Rescale templates independently of AP

### ISSUE THREAD

**Issue by rdnv** [seshnadathur/void-galaxy-cosmo-fitter#10]
Missing option to rescale templates independently of the AP parameters provided. 

![output_AP_template_rescaling](https://github.com/seshnadathur/victor/assets/33979685/df88f37f-6968-4ba1-a503-0c1d7e756e98)

**Comment by seshnadathur** [comment]
Not sure what the line labelled "changes" is showing (and I can't see it either).

**Comment by seshnadathur** [comment]
I'd like to see a sanity check that when you set the value of astar to the same rescaling value as you would derive from the old AP-based method, you recover the old result. (In addition to showing that you can independently set a different value of astar, as in the figure above.)
