### ISSUE TITLE
True cosmology

### ISSUE THREAD

**Issue by rdnv** [seshnadathur/void-galaxy-cosmo-fitter#14]
The calculations in theory_xi should all be done in the true cosmology, so iaH_true should be used. 

![output_AP_theory_fix](https://github.com/seshnadathur/victor/assets/33979685/2dd8a198-1675-45c4-8fc6-0f4e0b267eca)

**Comment by rdnv** [comment]
\alpha_* needs to multiply velocity v_r if templates are used

**Comment by rdnv** [comment]
The same as orange lines above, after merging changes to velocity_profiles() and theory_xi(), showing that changes cancel out. 

![image](https://github.com/seshnadathur/victor/assets/33979685/3f16cee1-1514-423c-ae49-3f05f63a84c0)

**Comment by seshnadathur** [comment]
This should be addressed by #11.
