### ISSUE TITLE
Minor bugs in ccf_model.py

### ISSUE THREAD

**Issue by rdnv** [seshnadathur/void-galaxy-cosmo-fitter#8]
On line 593 in theory_xi() velocity derivative should be rescaled as dv_true/dr_true = dv_true/dr_fid * dr_fid/dr_true. 
On line 600 mu should not be rescaled since r_par and r_perp are rescaled:
r_perp_true = (S_fid * mu_fid) * aperp

![output_AP_bugfix](https://github.com/seshnadathur/victor/assets/33979685/a7b160e8-956b-4e04-ad33-5e457b7867be)

**Comment by seshnadathur** [comment]
Agree with this.
